### ISSUE TITLE
Creating a unit test suite for the R Package

### ISSUE THREAD

**Issue by meetagrawal09** [cytoscape/RCy3#200]
Currently I see that there are no unit tests added to the `tests` folder. I propose to add a well written test suite to improve reliability on the package functions.

**Comment by AlexanderPico** [comment]
We keep our tests here: https://github.com/cytoscape/RCy3/blob/devel/inst/unitTests/test_RCy3.R

As a Bioconductor project, if we add to the default`tests`folder, then they would automatically run (and fail) on their platform since they do not support having the Cytoscape application installed and running, which is a requirement for the RCy3 package.

Nevertheless, our test suite is by no means complete. We have a sister project [py4cytoscape](https://github.com/cytoscape/py4cytoscape/tree/master/tests) that does the same thing (wraps the functionality of CyREST) for Python that RCy3 does for R. It has a much more thorough and up-to-date test suite; one that we'd like to replicate so they could be developed in parallel going forward.

Given this information, are you still interested in working on such a test suite?

**Comment by meetagrawal09** [comment]
Thanks for directing me to the right place. I am currently going through the functions and existing tests. 
I have 2 questions though : 

1. Do we need tests for functions in `RCy3-utils` or the tests should be focused around functions that are exported ?
2. Do you plan to release the package on _CRAN_ ?

**Comment by AlexanderPico** [comment]
1. I don't have a strong opinion
2. Nope. Bioconductor is best for this package
