### ISSUE TITLE
Running RCy3 to import nested networks into cytoscape

### ISSUE THREAD

**Issue by shagupta13** [cytoscape/RCy3#213]
Hi 

I have been trying to use RCy3 to import nested networks from R to Cytoscape and I run into the issue that I have no way of specifying source and target columns with the function "importNetworkFromFile". I have both just loaded the .nnf file directly into Cytoscape or used "loadTableData" to generate multiple non-nested networks using RCy3 but haven't found a good way to just go from R script to nested network in Cytoscape directly. 

The general format for any line in this type of file (.nnf) is:

```
<network_name> <node1> <interaction> <node2>
OR
<network_name> <node1>
```

I have also attached an example nnf file below.

[NestedExample1.txt](https://github.com/cytoscape/RCy3/files/13046663/NestedExample1.txt)

I converted it to ".txt" as I am unable to upload a ".nnf" file format here.

Thank you for your help!

**Comment by AlexanderPico** [comment]
> To give more context, I was trying to use the netGSA package in R to upload the network of significant pathways found after enrichment analysis and their function for the upload fails because they generate a ".nnf" file on the backend.

**Comment by AlexanderPico** [comment]
Ok. I understand the .nnf format and can imagine a few ways to read this into Cytoscape via RCy3. In order to pick one, I'd need to know more about what you want to see in Cytoscape. For example do you want to see:

1. Protein nodes with boolean columns in the Node Table indicating membership in each GO term?
2. Protein and GO terms nodes with "interaction" and "membership" edges?
3. GO terms as Group Nodes with protein nodes as child nodes? (since a protein can belong to more than one, we'll have to choose the Group Node visualization carefully)

Do you have a particular visualization in mind already? Do you have a particular analysis you want to do next, after loading into Cytoscape?
