### ISSUE TITLE
Installation dependency issue uchardet

### ISSUE THREAD

**Issue by ammaralsheik** [cytoscape/RCy3#218]
When attempting to install RCy3 for R4.2.3, I get a dependency error with this package: uchardet

ERROR: dependency ‘uchardet’ is not available for package ‘RCy3’

I tried install the package as follows with no success as this package is not available for my version of R.

install.packages("uchardet", repos = "https://cloud.r-project.org/")
install.packages("uchardet")

Please advice.

**Comment by AlexanderPico** [comment]
Hi. We noticed in November that uchardet was no longer available from CRAN and implemented a replacement, released as RCy3 2.22.1. This latest version of RCy3 available via Bioconductor does no depend on uchardet and should not attempt to install it.

However, since you mention R4.2.3, I suspect you are trying to work with an older version? 

The solution is to update R and your Bioconductor packages, including RCy3. Then the uchardet dependency will be resolved. The only way to continue working with older versions is to maintain older installations (where you might have previously installed uchardet, for example). Otherwise, the best practice is to update R and Bioconductor packages per their release cycles.

**Comment by AlexanderPico** [comment]
If you _really, really, really_ need to install an older version, then you have to track down archived versions of discontinued packages and install them manually (e.g., [here](https://cran.r-project.org/src/contrib/Archive/uchardet/)). 

You will be getting software that has known bugs and is missing newer features though, so this is not recommended.

**Comment by ammaralsheik** [comment]
Thank you very much for your prompt response, I was able to resolve the issue through installing an archived version of that package as the R version is controlled by my institution.
