### ISSUE TITLE
Reproducible Workflow

### ISSUE THREAD

**Issue by GuntaasShergill** [cytoscape/RCy3#226]
Hello, 

I hope you're doing well. Thank you for creating this package. I had 2 questions, pertaining to creating a reproducible workflow:

1. Is there a way to use RCy3 to generate the same networks each time by setting a seed? I question the presentability of the my results if am unable to recreate it, thus I was looking for a way to make network generation reproducible. 

2. I am using WGCNA, so I am creating networks using Adjacency and TOM. Interestingly Cytoscape (individually and with RCy3) treats Adjacency as a weight in the form of distance (nodes with higher weight further away) whereas TOM weight is interpreted in the form of strength of connection (nodes with higher weight closer). Is there any way to explicitly indicate to RCy3 that weight should be interpreted as strength of connection. 

Thank you so much for your time and attention!

**Comment by AlexanderPico** [comment]
Thanks for your questions!

1. Overall, RCy3 does not have a random or stochastic step requiring a seed. It should reproduce the same output every time. Perhaps there is a particular layout or app you are using that does have a random step? I'd need to know which step you believe requires seed in order to advise on how to provide it.  In general, one of the main reasons I use RCy3 is to reproduce work and I don't provide a seed.

2. If you look at the settings for any Cytoscape edge-weighted layout (screenshot) you have the option to set how you want the weights to be treated. You can set any of these parameters via RCy3. I often test out the syntax via the Command Line interface (screenshot). Try: help layout force-directed to see all the options.
 
<img width="553" alt="Screenshot 2024-11-12 at 3 35 01 PM" src="https://github.com/user-attachments/assets/02d5de42-d8c2-43df-8492-1e88ef56ef9c">

<img width="748" alt="Screenshot 2024-11-12 at 3 37 20 PM" src="https://github.com/user-attachments/assets/2efb19d0-af36-404e-b597-54056245d4e8">

**Comment by GuntaasShergill** [comment]
Thank you so much for the response Dr. Pico!

1. I was using Edge-Weighted Spring Embedded layout (Kamada-Kawai), this must have been the root cause of the randomness as I do not observe the randomness in network generation in prefuse force directed layout - as you pointed out. I will continue to use this layout. Thank you!

2. I was experimenting with this prior to using RCy3 and for some reason upon changing settings particularly "Edge column that contains the weight" and "How to interpret weight values" however it doesn't seem clicking "apply layout" reflects those changes. I have attached pictures of the plot before and after applying layout, the color represents the pearson correlation relative to the central gene (who's adjacency I'm showing relative to all other genes), so dark green and red nodes should be closer to the circle (as seen in the before plot), since weights are based on adjacency (power function applied pearson correlation) but it becomes random after applying layout. 

Choosing the correct options, clicking done, and generating the networks again using RCy3, instead of applying layout seems to bring the desired result - however, only when using "normalized value". When choosing "1 - normalized value", the layout is once again random rather than inverse of the "normalized value" layout.

3. Something I noticed, which is trivial, is that I'm unable to create a network: createNetworkFromDataFrames(), when using node (500 nodes) and edge files (500x500 = 250000 edges) which create a network larger than the view threshold on cytoscape prompting the popup "Do you want to create a view for your large networks now?". The code does not progress past this line (I waited 5-6 minutes), so I manually loaded the network from table, on cytoscape  and it took only 10 seconds, so I don't believe this issue is associated with the network being too large). I then proceeded with the rest of the RCy3 code to make the desired modifications. Is this an issue on my end? As I assume many people use RCy3 to create large networks everyday. 

Overall, my problem is resolved thanks to your generous input and any further feedback would just be a plus. Thank you so much for your time and insight

Plot Before: 
<img width="499" alt="Plot Before" src="https://github.com/user-attachments/assets/6c14ff1a-0b5d-491c-8bfe-bdd547830e9d">

Settings: 
<img width="544" alt="Settings" src="https://github.com/user-attachments/assets/cdc2f610-3e61-4306-a9be-c4dcdaa398ef">

Plot After: 
<img width="516" alt="Plot After" src="https://github.com/user-attachments/assets/fe95c0a6-03d1-44e0-8a3c-238bf747754e">
